---
- name: Install cmatrix
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Install cmatrix
      community.general.homebrew:
        name:
          - cmatrix
        state: present
        update_homebrew: true

    - name: Check for Homebrew
      ansible.builtin.import_tasks: tasks/homebrew_check.yml

    - name: Create Developer directory
      ansible.builtin.import_tasks: tasks/create_dev_dir.yml

  roles:
    - common
    - devops
    - { role: zsh, zsh_p10k_dest: ~/.config/zsh/plugins }
