# - name: Add Hashicorp repo/tap to Homebrew
#   command: brew tap hashicorp/tap

- name: Install devops tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - awscli
    # local github action testing
    - act
    # - tfenv
    # - opentofu
    # - terraform
    - docker
    - ansible
    - ansible-lint
    # - utm
    - drawio
    # - aws-vault
    # - hashicorp/tap/vault
    # - vagrant
    # local aws
    - localstack
    - awscli-local
    - terraform-local
    - gitlab-ci-local
    # k8s local cluster
    - minikube
    - kind
# Openbao