---
- name: Copy p10k config
  ansible.builtin.copy:
    src: powerlevel10k/
    dest: "{{ zsh_p10k_dest }}"
    mode: "644"
  loop:
    - powerlevel10k/
    - .p10k.zsh

- name: Copy .zshrc to home directory
  ansible.builtin.template:
    src: .zshrc.j2
    dest: ~/.zshrc
    mode: "644"
